#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")

--[[
default=(
  padding_left=5
  padding_right=5
  icon.font="MesloLGL Nerd Font Mono:Bold:17.0"
  label.font="MesloLGL Nerd Font Mono:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --bar position=top height=38 color=0xff349052
sketchybar --add item battery right
sketchybar --set battery label="100%"
--]]
